language: php

# lock distro so future defaults will not break the build
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - name: "Build phar"
      php: 7.2
      script: composer build
    - name: "Test dependency installation"
      php: 7.2
      install: []
      script: composer install --dry-run --working-dir=tests/install-as-dep
    - php: hhvm-3.18
  allow_failures:
    - php: hhvm-3.18

sudo: false

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
